# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af0e2cc0615615ffef8d175eacf88b8d829533d073707ac378675384a517d111dcde1cb07eab3c01f97249ae4507c99257a66e33a2ad98c5013b0e0e0c59a5a3

test:
  secret_key_base: 25242f577fb91a6dec85aa67c0f0c26676c5de082214ecbd10ee8732794623957b7c83785425cdfa8a4b33950c7fc19ae8f465e234ec0c52ba63ced3e9ff78cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
